# docker-compose for Fat controller example stack
#
version: "2.4"
services:

  fat-controller:
    privileged: true
    extends:
      service: fat-controller
      file: ../docker-compose.yml
    ports:
      - 8080:8080
    volumes:
      - ./controller.conf:/etc/controller.conf

      # this assumes you are running in folder above this file
      - .:${PWD}/example

    environment:
      # this assumes you are running in folder above this file
      COMPOSE_CONTEXT: ${PWD}/example

volumes:
  sockets: