#
# docker-compose for fatc stack
#
# run this composition from the parent directory
#
# eg:
#     . test.env
#     docker-compose up -d
#

version: "2.4"
services:
  app:
    image: busybox
    depends_on:
      fatc:
        condition: service_healthy

  fatc:
    image: phlax/fatc
    # required for systemd logging
    tty: true

    # required to do bind mount inside - see docker workaround below
    # cap_add:
    #   - SYS_ADMIN
    # NOT NEEDED! - maybe needed by travis or by docker...
    privileged: true

    volumes:
      # docker socket
      # - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/fatc/docker:/var/lib/docker

      # systemd requirement
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # fatc configuration
      - ${PWD}/example/etc/config.json:/etc/fatc/config.json

      # the easiest config for sockets is using a real file path
      # preferably one mounted on tmpfs
      # - /var/run/fatc/sockets:/var/run/fatc/sockets
      - ${PWD}/example/sockets:/var/run/fatc/sockets

      - ${PWD}/example/templates:/var/lib/fatc/templates-registry

    tmpfs:
      # systemd requires these to be on tmpfs
      - /run
      - /run/lock
      - /tmp
    ports:
      # required to connect to network daemons
      - 8082:8082
      - 8083:8083

      # required to connect to network services
      - 8092:8092
      - 8093:8093
    healthcheck:
      interval: 10s
      retries: 20
      test: systemctl status | grep running
