# docker-compose for Fat controller example stack
#
version: "2.4"
services:

  fat-controller:
    privileged: true
    extends:
      service: fat-controller
      file: ../docker-compose.yml
    # zmq subscriber socket should be started first, if used
    depends_on:
    - zmq
    ports:
      - 8080:8080
    volumes:
      - ./controller.conf:/etc/controller.conf
      - sockets:/sockets
      - ctrl-sockets:/controller/sockets
      - logs:/var/log/nginx:ro

      # this assumes you are running in folder above this file
      - .:${PWD}/example

    environment:
      # this assumes you are running in folder above this file
      COMPOSE_CONTEXT: ${PWD}/example
      USE_CRIU: 'true'

  zmq:
    restart: 'no'
    image: phlax/zmq
    environment:
    - ZMQ_APP_subscriber=ctrl.zmq.pubsub.ZMQSubscriber ipc:///app/sockets/zmq-subscriber.socket ctrl
    - ZMQ_APP_rpc=ctrl.zmq.rpc.ZMQRPCClient ipc:///app/sockets/zmq-rpc.socket
    - ZMQ_APP_cli=ctrl.zmq.rpc.ZMQRPCServer ipc:///sockets/zmq-cli.socket
    - ZMQ_ROUTER=myrouter.ConfiguredRouter
    volumes:
    - ctrl-sockets:/app/sockets
    - ./myrouter.py:/app/src/myrouter.py

volumes:
  logs:
  sockets:
  ctrl-sockets:
