#
# docker-compose for fatc stack
#
# run this composition from the parent directory
#
# eg:
#     . test.env
#     docker-compose up -d
#

version: "2.4"
services:
  app:
    image: busybox
    depends_on:
      fatc:
        condition: service_healthy
      external-http:
        condition: service_healthy

  fatc:
    image: phlax/fatc
    # required for systemd logging
    tty: true

    # required to do bind mount inside - see docker workaround below
    # cap_add:
    #   - SYS_ADMIN
    # NOT NEEDED! - maybe needed by travis or by docker...
    privileged: true

    volumes:
      # docker socket
      # - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/fatc/docker:/var/lib/docker

      # systemd requirement
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

      # the easiest config for sockets is using a real file path
      # preferably one mounted on tmpfs
      # - /var/run/fatc/sockets:/var/run/fatc/sockets
      - ${PWD}/example/sockets:/var/run/fatc/sockets

      # this is used to determine where to send :backend: requests
      # - /var/lib/fatc/backend:/var/lib/fatc/backend:ro
      - ${PWD}/example/backend:/var/lib/fatc/backend:ro

      - ${PWD}/example/daemon0:/var/lib/fatc/daemons/daemon0
      - ${PWD}/example/daemon1:/var/lib/fatc/daemons/daemon1
      - ${PWD}/example/daemon2:/var/lib/fatc/daemons/daemon2
      - ${PWD}/example/daemon3:/var/lib/fatc/daemons/daemon3
      - ${PWD}/example/daemon4:/var/lib/fatc/daemons/daemon4

      - ${PWD}/example/service0:/var/lib/fatc/services/service0
      - ${PWD}/example/service1:/var/lib/fatc/services/service1
      - ${PWD}/example/service2:/var/lib/fatc/services/service2
      - ${PWD}/example/service3:/var/lib/fatc/services/service3
      - ${PWD}/example/service4:/var/lib/fatc/services/service4
      - ${PWD}/example/service5:/var/lib/fatc/services/service5

    tmpfs:
      # systemd requires these to be on tmpfs
      - /run
      - /run/lock
      - /tmp
    networks:
      - fatc-external
    ports:
      # required to connect to network daemons
      - 8082:8082
      - 8083:8083

      # required to connect to network services
      - 8092:8092
      - 8093:8093
      - 8095:8095
    healthcheck:
      interval: 10s
      retries: 20
      test: systemctl status fatc | grep active

  external-http:
    image: nginx
    volumes:
      - ${PWD}/example/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${PWD}/example/index.html:/usr/share/nginx/html/index.html:ro
    networks:
      fatc-external:
    healthcheck:
      interval: 10s
      retries: 20
      test: service nginx status || exit 1

networks:
  # this network is outside of the fatc docker but containers inside can
  # see the containers here
  fatc-external:
