# https://travis-ci.org/#!/phlax/fat-controller
dist: trusty
sudo: true
language: python
services:
  - docker

before_install:
  - "echo '{\"storage-driver\": \"overlay2\", \"experimental\": true}' | sudo tee /etc/docker/daemon.json"
  - "sudo apt-get install -qq -y --allow-downgrades docker-ce=17.05.0~ce-0~ubuntu-trusty"

install:
  - sudo apt-get install -qq -y libprotobuf-c0 libprotobuf-lite8 libnet1 libnl-3-200 iptables
  # - sudo apt-get install -qq -y bzip2 libprotobuf-dev libprotobuf-c0-dev protobuf-c-compiler protobuf-compiler python-protobuf libnl-3-dev libcap-dev libnet1-dev build-essential
  - pip install -U docker-compose
  - CRIU_CONTAINER=$(docker run -d --rm phlax/debian-criu:ubuntu-trusty)
  - sudo docker cp $CRIU_CONTAINER:/usr/local/bin/criu /usr/local/bin/criu
  - docker kill $CRIU_CONTAINER
  - cd /home/travis/build/phlax/fat-controller

script:

  - docker version

  # build the fat controller
  - docker-compose build fat-controller

  # set the environment
  - echo "COMPOSE_FILE=./example/docker-compose.controller.yml" > ./.env
  - echo "COMPOSE_IGNORE_ORPHANS='true'" >> ./.env
  - envsubst < example/controller.conf.in > example/controller.conf

  # up...
  - docker-compose up -d fat-controller

  - docker-compose exec fat-controller journalctl -u controller
  - docker-compose exec fat-controller journalctl -u configuration
  - docker-compose exec fat-controller journalctl -u daemon-controller

  # nginx is not active
  - docker-compose exec fat-controller docker-compose ps
  - docker-compose exec fat-controller systemctl show controller-nginx -p ActiveState

  # fetch a page
  - curl -m 5 http://localhost:8080

  # nginx is active now
  - docker-compose exec fat-controller docker-compose ps
  #  - docker-compose exec fat-controller systemctl status -l --no-pager controller-nginx
  - docker-compose exec fat-controller journalctl --all -l --no-pager -u controller-nginx
  - docker-compose exec fat-controller systemctl show controller-nginx -p ActiveState

  # stop nginx, checkpoint was created
  - docker-compose exec fat-controller systemctl stop controller-nginx
  - docker-compose exec fat-controller docker-compose ps
  - docker-compose exec fat-controller systemctl show controller-nginx -p ActiveState
  - docker checkpoint ls example_nginx_1

  # request a page again
  - curl -m 5 http://localhost:8080

  # nginx is back - checkpoint was destroyed
  - docker-compose exec fat-controller docker-compose ps
  - docker-compose exec fat-controller systemctl status -l --no-pager controller-nginx
  - docker-compose exec fat-controller systemctl show controller-nginx -p ActiveState
  - docker checkpoint ls example_nginx_1

  # wait for 10 seconds and nginx should have gone away
  - sleep 10

  - docker-compose exec fat-controller docker-compose ps
  - docker-compose exec fat-controller journalctl -l --no-pager -u idle.timer
  - docker-compose exec fat-controller journalctl -l --no-pager -u idle.service
  - docker-compose exec fat-controller journalctl -l --no-pager -u controller-nginx
  - docker-compose exec fat-controller systemctl show controller-nginx -p ActiveState
  - docker checkpoint ls example_nginx_1

  # request a page again, and its back
  - curl -m 5 http://localhost:8080
  - sleep 1

  - docker checkpoint ls example_nginx_1

  - docker-compose stop fat-controller
  - docker ps -a
  - docker logs example_nginx_1

after_success:

  - docker-compose build fat-controller
  - docker login -u phlax -p "$DOCKER_PASSWORD"
  - docker push phlax/fat-controller
