# https://travis-ci.org/#!/phlax/fatc

dist: bionic
language: python
env:
  global:
    - PYTHONUNBUFFERED=1

before_install:
  - # echo '{"experimental":true,"storage-driver":"devicemapper"}' | sudo tee /etc/docker/daemon.json
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - >
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    && sudo apt update
    && sudo apt -y -o Dpkg::Options::="--force-confnew" install docker-ce criu

install:
  - make image
  - make pysh
  - make cli

script:
  - . test.env

  # this points to an http server in a docker container, but allows realtime updating of where
  # fatc sends :backend: traffic to allow scaling and movable workloads
  - sudo mkdir -p /var/lib/fatc
  - echo external-http > example/backend
  - pysh ./tests/system.sh
  - pysh ./tests/daemons.sh
  - pysh ./tests/services.sh

  - shellcheck -x usr/lib/fatc/*
  - shellcheck -x usr/bin/*


before_deploy:
  - echo $DOCKER_PASSWORD | docker login -u phlax --password-stdin

deploy:
  provider: script
  script: make hub-image
  skip_cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master)$
