# docker-compose for Fat controller stack
#
version: "2.4"
services:

  fat-controller:
    image: phlax/fat-controller
    build:
      context: ./docker
    volumes:
      - /var/run/docker.sock:/fat/docker.sock
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - sockets:/sockets
    privileged: true
    environment:
      DOCKER_HOST: 'unix:///fat/docker.sock'
      COMPOSE_CONTEXT: ${PWD}
      COMPOSE_IGNORE_ORPHANS: 'true'

volumes:
  sockets: