# docker-compose example for Fat controller services stack: unix -> unix
#
# This service listens on a backend unix socket.
#
# Fat controller creates a frontend unix socket for it and proxies to the backend
# unix socket
#
# redis is added, to show how the service can network with other containers in its
# own stack

version: "2.4"
services:
  app:
    image: busybox
    depends_on:
      http:
        condition: service_healthy
      redis:
        condition: service_healthy

  http:
    image: nginx
    depends_on:
      - redis
    volumes:
      - /var/lib/controller/services/service0/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/lib/controller/services/service0/index.html:/usr/share/nginx/html/index.html:ro
      # some service here must create a socket in /var/run/controller/sockets/service.0.sock
      - /var/run/controller/sockets/services/service0:/var/run/controller/sockets
    healthcheck:
      interval: 10s
      retries: 20
      test: "service nginx status || exit 1"

  redis:
    image: redis
    healthcheck:
      interval: 10s
      retries: 20
      test: "redis-cli ping | grep PONG"
