#!/bin/bash

set -e

SERVICE=$1
TARGET_CONTAINER=$2

docker start --checkpoint=$SERVICE $TARGET_CONTAINER
echo "Restored $SERVICE from checkpoint"
docker checkpoint rm $TARGET_CONTAINER $SERVICE
echo "Removed checkpoint for: $SERVICE"
