#!/bin/bash

set -e

APP=apps
DC_FILE=/var/lib/controller/docker-compose.yml

if [ -f "$DC_FILE" ]; then
    docker-compose  -f $DC_FILE -p $APP up -d
else
    echo "No compose file found for daemons"
fi
