#!/bin/bash

set -e

SOCKET=$1
SERVICES=${@:2}

echo "Spawning services: $SERVICES"

cores=$(fgrep -c processor /proc/cpuinfo)

export COMPOSE_IGNORE_ORPHANS=true


if [ -S "$SOCKET" ]; then
    if [ -z $(/usr/local/bin/docker-compose --skip-hostname-check ps -q --filter 'status=running' $SERVICE)  ]; then
        exit 0
    else
        echo "Removing stale socket: $SOCKET"
        rm $SOCKET;
    fi
fi

printf '%s\n' "${SERVICES[@]}" | xargs --max-procs=$cores  \
      --replace \
      --verbose \
      /bin/sh -c "echo starting {} && COMPOSE_IGNORE_ORPHANS=true /usr/local/bin/docker-compose --no-ansi --skip-hostname-check up -d --no-build --no-recreate {}"
