#!/bin/bash

APP=$1
NAME=$2
SOCKET=$3
SERVICE=$4

if [[ $SOCKET == /* ]]; then
    DC_FILE=/var/lib/controller/$NAME/docker-compose.yml
    export DOCKER_HOST=unix:///fat/docker.sock
    echo "Stopping service $SERVICE..."
    TARGET_CONTAINER="${APP}_${SERVICE}_1"
    if [ ! -z "$USE_CRIU" ]; then
        docker checkpoint create $TARGET_CONTAINER $SERVICE
    else
        DC="/usr/local/bin/docker-compose -p $APP -f $DC_FILE --skip-hostname-check --no-ansi"
        $DC stop $SERVICE
        if [ -S "$SOCKET" ]; then
            echo "Stopped $SERVICE, waiting for socket to go away..."
            until [ ! -S "$SOCKET" ]; do
                sleep .5
            done
        fi
    fi
fi
