#!/bin/bash

APP=$1
NAME=$2
SOCKET=$3
SERVICE=$4

DC_FILE=/var/lib/controller/$NAME/docker-compose.yml
export DOCKER_HOST=unix:///fat/docker.sock


echo "Stopping service $SERVICE"
TARGET_CONTAINER="${APP}_${SERVICE}_1"
docker checkpoint create $TARGET_CONTAINER $SERVICE
