#!/bin/bash

APP="$1"
NAME="$2"
SOCKET="$3"
SERVICE="$4"

DC_FILE=/var/lib/controller/$NAME/docker-compose.yml

echo "Checking service $SERVICE on $SOCKET"

until [ -S "$SOCKET" ] && [ "$(/usr/local/bin/docker-compose -p $APP ps --services --filter 'status=running' $SERVICE)" ]; do
    sleep 0.1;
done
