#!/bin/bash -e

. /usr/lib/fatc/common


fatc_edit_docker_config () {
    if [ ! -f /etc/docker/daemon.json ];then
	mkdir -p /etc/docker
	echo '{"experimental": true, "storage-driver": "overlay2"}' >> /etc/docker/daemon.json
    else
	jq '.experimental = true' /etc/docker/daemon.json \
	    | sponge /etc/docker/daemon.json
	jq '.storage-driver = "overlay2"' /etc/docker/daemon.json \
	    | sponge /etc/docker/daemon.json
    fi
    if systemctl is-system-running; then
	systemctl reload docker.service
    fi
}


fatc_create_docker_env () {
    mkdir -p "$FATC_LIB"
    chown fatc:fatc "$FATC_LIB"
    cd "$FATC_LIB"
    if [ ! -d "$FATC_BIN" ]; then
        su - fatc -s /bin/bash -c "\
    		virtualenv . -p /usr/bin/python3 \
		&& . bin/activate \
		&& pip install docker-compose"
    fi
}
