#!/bin/bash -e


. /usr/lib/fatc/common


fatc_start () {
    fatc_log "Fatc started"
}


fatc_stop () {
    fatc_log "Fatc stopped"
    docker container prune -f && docker network prune -f && docker volume prune -f && docker image prune -f
}
