#!/bin/bash -e


. /usr/lib/fatc/common


fatc_start_service () {
    # only the socket - ie no stack is activated for services
    # stacks are activated dynamically when the socket is tickled
    local i
    i=0
    for _ in $(fatc_get_tracks service "$1"); do
	systemctl start "fatc.service.${1}.${i}--proxy.socket"
	i=$((i + 1))
    done
}


fatc_start_daemon () {
    local compose i
    i=0
    for _ in $(fatc_get_tracks daemon "$1"); do
	systemctl start "fatc.daemon.${1}.${i}--proxy.socket"
	i=$((i + 1))
    done
    compose=$(fatc_get_stack_compose daemon "$1")
    if [ -f "$compose" ]; then
	systemctl start "fatc.daemon.${1}"
    fi
}


fatc_start () {
    export -f fatc_start_service
    export -f fatc_start_daemon
    export -f fatc_log
    export -f fatc_log_warn
    export -f fatc_log_err
    export -f fatc_get_stack_compose
    export -f fatc_get_tracks
    export -f fatc_get_stack_dir
    export FATC_DAEMONS
    export FATC_SERVICES
    export FATC_CONFIG
    export FATC_STACK_CONFIG

    fatc_configure_parallel start service
    fatc_configure_parallel start daemon
}


fatc_stop () {
    fatc_log "Fatc stopped"

    for socket in ls_files /etc/systemd/system/fatc.*--proxy.socket; do
	echo "STOPPING SOCKET $socket"
    done
    echo "START WAITING FOR SOCKETS TO STOP LISTENING"
    sleep 10
    echo "FINISH WAITING FOR SOCKETS TO STOP LISTENING"
}


fatc_stop_wait () {
    echo "TOTALLY STOPPED WAITING FOR SOCKETS"
}


fatc_cleanup () {
    echo "FATC CLEANUP: make sure all containers have been stopped!"
    docker ps
    docker container prune -f && docker network prune -f && docker volume prune -f && docker image prune -f
}
