#!/bin/bash -e


. /usr/lib/fatc/common


fatc_proxy_start () {
    local backend upstream
    if [[ "$5" = :backend:* ]]; then
	backend=$(fatc_backend_resolve "${@}")
	upstream="${5//:backend:/${backend}:}"
    else
	upstream=$(fatc_get_upstream "$5" "$1")
    fi
    exec /lib/systemd/systemd-socket-proxyd "$upstream"
}
