#!/bin/bash

LOAD=${LOAD:-"load_services"}


load_services () {
    curl -m20 --unix-socket ./example/sockets/fc/service0.0.sock http://localhost | grep Hello | grep backend | grep unix
    curl -m20 --unix-socket ./example/sockets/fc/service1.0.sock http://localhost | grep Hello | grep backend | grep network
    docker-compose exec tail -f /var/log/syslog
}


make image
docker-compose down && docker container prune -f && docker-compose up -d
echo "Running $LOAD"
$LOAD
